### ISSUE TITLE
diff-cover --external-css-file fails with TemplateNotFound

### ISSUE THREAD

**Issue by mgedmin** [Bachmann1234/diff-cover#37]
It looks like https://pypi.python.org/packages/source/d/diff_cover/diff_cover-0.9.0.tar.gz is missing some files in the `templates/` directory, and so the new feature introduced by #35 doesn't work:
```
diff-cover --html-report var/diff-cover/index.html --external-css var/diff-cover/style.css var/coverage.xml
Traceback (most recent call last):
  File "bin/diff-cover", line 22, in <module>
    sys.exit(diff_cover.tool.main())
  File "/var/lib/jenkins-slave/workspace/labtarna-branch/eggs/diff_cover-0.9.0-py2.7.egg/diff_cover/tool.py", line 286, in main
    ignore_unstaged=arg_dict['ignore_unstaged'],
  File "/var/lib/jenkins-slave/workspace/labtarna-branch/eggs/diff_cover-0.9.0-py2.7.egg/diff_cover/tool.py", line 220, in generate_coverage_report
    reporter.generate_css(output_file)
  File "/var/lib/jenkins-slave/workspace/labtarna-branch/eggs/diff_cover-0.9.0-py2.7.egg/diff_cover/report_generator.py", line 230, in generate_css
    template = TEMPLATE_ENV.get_template(self.CSS_TEMPLATE_NAME)
  File "/var/lib/jenkins-slave/workspace/labtarna-branch/eggs/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 812, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/var/lib/jenkins-slave/workspace/labtarna-branch/eggs/Jinja2-2.8-py2.7.egg/jinja2/environment.py", line 774, in _load_template
    cache_key = self.loader.get_source(self, name)[1]
  File "/var/lib/jenkins-slave/workspace/labtarna-branch/eggs/Jinja2-2.8-py2.7.egg/jinja2/loaders.py", line 235, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: external_style.css
```

I recommend https://pypi.python.org/pypi/check-manifest to avoid this kind of issue in the future ;)

**Comment by mgedmin** [comment]
Uhh I'm afraid I'm still seeing this with 0.9.1.

**Comment by Bachmann1234** [comment]
well dang it. 

So I verified the 9.0.1 tag does have your PR in it. Ill see if I can find some time to play with this in the evening but if you figure it out dont let me slow you down.

**Comment by Bachmann1234** [comment]
@mgedmin give it a shot with 0.9.2. The files were in the manifest but were not included in setup.py so the css never got copied over. My bad, I should have saw that in review.

**Comment by mgedmin** [comment]
Welp, I completely forgot that there are two copying steps: source tree -> sdist *and* sdist -> installed files.  My bad for not actually testing PR #38 locally before assuming it was sufficient!
