### ISSUE TITLE
Pylint fails to run if no pylintrc is present

### ISSUE THREAD

**Issue by KenjiTakahashi** [Bachmann1234/diff-cover#58]
```bash
$ diff-quality --violations=pylint
Traceback (most recent call last):
  File "/home/kenji/.virtualenvs/whmonit/bin/diff-quality", line 11, in <module>
    sys.exit(main())
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/tool.py", line 344, in main
    ignore_unstaged=arg_dict['ignore_unstaged'],
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/tool.py", line 266, in generate_quality_report
    reporter.generate_report(output_file)
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/report_generator.py", line 216, in generate_report
    report = template.render(self._context())
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/report_generator.py", line 260, in _context
    (src, self._src_path_stats(src)) for src in self.src_paths()
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/report_generator.py", line 83, in src_paths
    return set(src for src, summary in self._diff_violations().items()
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/report_generator.py", line 176, in _diff_violations
    ) for src_path in self._diff.src_paths_changed()
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/report_generator.py", line 176, in <genexpr>
    ) for src_path in self._diff.src_paths_changed()
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/violationsreporters/base.py", line 157, in violations
    output, _ = execute(command)
  File "/home/kenji/.virtualenvs/whmonit/lib/python2.7/site-packages/diff_cover/command_runner.py", line 43, in execute
    raise CommandError(stderr)
diff_cover.command_runner.CommandError: No config file found, using default configuration
```
This is certainly true that there's no config file, but why is it a fatal error? It should let it do as it says :-). [`touch .pylintrc` works around it, of course.]

**Comment by peterg79** [comment]
https://github.com/Bachmann1234/diff-cover/pull/70 should fix this issue.

**Comment by Bachmann1234** [comment]
https://pypi.python.org/pypi/diff_cover/1.0.2
