### ISSUE TITLE
`diff-quality --violations=pylint` fails because of innocuous stderr output from pylint

### ISSUE THREAD

**Issue by barrywhart** [Bachmann1234/diff-cover#71]
This started happening today -- I'm guessing it's due to a recent change in `pylint`.

If I run `diff-quality --violations=pylint`, it fails with the following output:

```
$ diff-quality --violations=pylint
> /usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/command_runner.py(53)run_command_for_code()
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/mcdsu-2.7.13/bin/diff-quality", line 11, in <module>
    sys.exit(main())
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/tool.py", line 376, in main
    exclude=arg_dict['exclude'],
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/tool.py", line 296, in generate_quality_report
    reporter.generate_report(output_file)
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/report_generator.py", line 216, in generate_report
    report = template.render(self._context())
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/report_generator.py", line 260, in _context
    (src, self._src_path_stats(src)) for src in self.src_paths()
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/report_generator.py", line 83, in src_paths
    return set(src for src, summary in self._diff_violations().items()
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/report_generator.py", line 176, in _diff_violations
    ) for src_path in self._diff.src_paths_changed()
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/report_generator.py", line 176, in <genexpr>
    ) for src_path in self._diff.src_paths_changed()
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/violationsreporters/base.py", line 157, in violations
    output, _ = execute(command)
  File "/usr/local/pyenv/versions/2.7.13/envs/mcdsu-2.7.13/lib/python2.7/site-packages/diff_cover/command_runner.py", line 43, in execute
    raise CommandError(stderr)
diff_cover.command_runner.CommandError: Using config file /opt/dev/src/.pylintrc
```

Note the stderr output does not indicate an actual error, it's simply notifying what configuration file `pylint` is using. This message is coming from [here](https://github.com/PyCQA/pylint/blob/master/pylint/config.py#L665-L668).

This occurs with diff_cover version 1.0.0 and pylint version 1.8.1.

**Comment by Bachmann1234** [comment]
Hmm, I believe we have a fix currently living on master that I intend to release soon

**Comment by Bachmann1234** [comment]
@peterg79  do I have that right?

**Comment by Bachmann1234** [comment]
I just need to find some time to actually do a release. This weekend by the latest...

**Comment by barrywhart** [comment]
Sounds great! BTW, I confirmed it does not fail if I downgrade to pylint 1.7.5.

**Comment by peterg79** [comment]
@Bachmann1234 that's right, version 1.0.2 will fix that. This issue is a variation of https://github.com/Bachmann1234/diff-cover/issues/58 - that is fixed in 1.0.2 too.

Basically, pylint enabled more output to stderr, and diff-quality considered it as an error. From 1.0.2 diff-cover looks at the exit code of the process to determine if the tool run properly.

**Comment by Bachmann1234** [comment]
Released! https://pypi.python.org/pypi/diff_cover/1.0.2

**Comment by barrywhart** [comment]
That's great! Thanks for the quick turnaround.
