### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by hjqgloria** [Bachmann1234/diff-cover#88]
Hi,

I use Coverlet to generate a coverage report in cobertura format for my .net project. But I got en error:
> AttributeError: 'NoneType' object has no attribute 'strip'

Have I done anything wrong here? 
`diff-cover coverage.cobertura.xml
Traceback (most recent call last):
  File "C:\Users\c624jh1\AppData\Local\Programs\Python\Python37-32\Scripts\diff-cover-script.py", line 11, in <module>
    load_entry_point('diff-cover==1.0.5', 'console_scripts', 'diff-cover')()
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\tool.py", line 350, in main
    src_roots=arg_dict['src_roots'],
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\tool.py", line 279, in generate_coverage_report
    reporter.generate_report(output_file)
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\report_generator.py", line 215, in generate_report
    report = template.render(self._context())
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\report_generator.py", line 259, in _context
    src: self._src_path_stats(src) for src in self.src_paths()
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\report_generator.py", line 83, in src_paths
    return {src for src, summary in self._diff_violations().items()
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\report_generator.py", line 175, in _diff_violations
    for src_path in self._diff.src_paths_changed()
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\report_generator.py", line 175, in <dictcomp>
    for src_path in self._diff.src_paths_changed()
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\violationsreporters\violations_reporter.py", line 230, in violations
    self._cache_file(src_path)
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\violationsreporters\violations_reporter.py", line 190, in _cache_file
    line_nodes = self._get_src_path_line_nodes_cobertura(xml_document, src_path)
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\violationsreporters\violations_reporter.py", line 103, in _get_src_path_line_nodes_cobertura
    classes = self._get_classes(xml_document, src_path)
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\violationsreporters\violations_reporter.py", line 85, in _get_classes
    [clazz for clazz in classes if
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\violationsreporters\violations_reporter.py", line 92, in <listcomp>
    ) for source in sources]]
  File "c:\users\c624jh1\appdata\local\programs\python\python37-32\lib\site-packages\diff_cover\violationsreporters\violations_reporter.py", line 92, in <listcomp>
    ) for source in sources]]
AttributeError: 'NoneType' object has no attribute 'strip'\`

**Comment by Bachmann1234** [comment]
So the problem seems to be in this section of the code

```python
# cobertura sometimes provides the sources for the measurements
        # within it. If we have that we outta use it
        sources = xml_document.findall('sources/source')
        sources = [source.text for source in sources]
        classes = [class_tree
                   for class_tree in xml_document.findall(".//class")
                   or []]

        classes = (
            [clazz for clazz in classes if
             src_abs_path in [
                 self._to_unix_path(
                     os.path.join(
                         source.strip(),
                         clazz.get('filename')
                     )
                 ) for source in sources]]
            or
            [clazz for clazz in classes if
             self._to_unix_path(clazz.get('filename')) == src_abs_path]
            or
            [clazz for clazz in classes if
             self._to_unix_path(clazz.get('filename')) == src_rel_path]
        )
```

We are basically hitting a NPE of sorts when hitting this statement

```
            [clazz for clazz in classes if
             src_abs_path in [
                 self._to_unix_path(
                     os.path.join(
                         source.strip(),
                         clazz.get('filename')
                     )
                 ) for source in sources]]
```

So some element of the sources array is `None`

What this tells me is that there is something missing in the cobertura xml that we assume is there. Is there anyway you can share it here?

**Comment by hjqgloria** [comment]
Hi Bachmann1234,

Thanks for your quick answer!
There is an empty source element at the beginning of the xml file:

`<coverage line-rate="0.178" branch-rate="0.348" version="1.9" timestamp="1545037553" lines-covered="675" lines-valid="3787" branches-covered="260" branches-valid="747">`
  `<sources>`
 ` <source></source>`
`  </sources>`
I removed the empty element then it worked. Is it possible for diff-cover remove the check on the empty elements?

**Comment by Bachmann1234** [comment]
Give https://pypi.org/project/diff-cover/1.0.6/ a shot
